"use client";

import { useLocalized } from "@/components/providers/locale-provider";
import { ChecklistExercise } from "@/components/summary/checklist-exercise";

const ITEMS = {
  en: [
    "Get 5-10 minutes of sunlight in my eyes within the first hour after waking (a 10,000 lux light if there's no sun)",
    "Hydrate, have my caffeine and move a little in that first hour; no phone in bed",
    "Exercise six days a week, ideally in the first half of the day, with one full rest day",
    "No caffeine in the 8 hours before sleep",
    "Dim the lights in the final hour of the day and keep my mind off work",
    "Do five long exhales during the day (or one long one before sleep)",
    "Either fully relax or fully work; stop doing a hybrid of the two",
    "Once a month, write my left column (concerns) and right column (what I can control)",
    "When my mind drifts to the left column, get present: literal actions, what I hear, see and feel",
    "Practice yoga nidra / NSDR for 10-30 minutes, 1-7 days a week (first thing in the morning after a bad night)",
    "Use the eye-movement trick when I wake at night: side, side, counterclockwise, clockwise, nose, exhale",
    "Check what state I'm in before opening social media",
    "Take myself seriously: act like a pro athlete in my field, including the rest",
    "Find my edge (the most real work I can sustain), then work around that average",
    "Make the day the unit of time: what can I do today, knowing I'm coming back tomorrow?",
    "Take one reset day a week (sunlight still, but no exercise and nothing to prove)",
    "When I freeze before a risk, lower the stakes: commit for three days, then three more",
    "Chop wood, carry water: on hard days, just do today's work without asking why",
    "Cold shower with walls: stay in past one more urge to get out (max 3 minutes, not ice)",
    "Do 10 breaths of meditation before getting out of bed",
    "Make my work sets harder, not easier",
    "When overwhelmed, dilate my gaze to take in the whole room, then pick things off one by one",
    "Recall something I survived or built, and own my part in it",
    "Do the slightly harder thing when I notice it",
    "Self-test after every book or podcast: what did I learn? Look up what I can't remember",
    "Never self-attack or attack others; if I can't do anything useful, do nothing for 5 minutes",
    "Keep a committee of people I respect to pressure-test big decisions",
    "Keep social media on a separate phone or in a lock box during focused work",
    'Ask "am I a consumer or a creator right now?" and spend some time creating every day',
    "Become the producer of the thing I consume the most",
  ],
  hi: [
    "जागने के पहले घंटे में 5-10 minutes आँखों में sunlight लेना (धूप न हो तो 10,000 lux light)",
    "उस पहले घंटे में पानी पीना, caffeine लेना और थोड़ा move करना; बिस्तर में phone नहीं",
    "हफ़्ते में छह दिन exercise, ideally दिन के पहले हिस्से में, एक दिन पूरा rest",
    "सोने से पहले के 8 घंटों में caffeine नहीं",
    "दिन के आख़िरी घंटे में lights dim करना और mind को काम से दूर रखना",
    "दिन में पाँच long exhales करना (या सोने से पहले एक लंबा)",
    "या तो पूरा relax या पूरा काम; दोनों का hybrid बंद",
    "महीने में एक बार अपना left column (चिंताएँ) और right column (जो मैं control कर सकता हूँ) लिखना",
    "जब mind left column में जाए, present हो जाना: literal actions, जो सुनता, देखता और महसूस करता हूँ",
    "हफ़्ते में 1-7 दिन 10-30 minutes yoga nidra / NSDR practice करना (बुरी रात के बाद सुबह सबसे पहले)",
    "रात को जागने पर eye-movement trick: एक तरफ़, दूसरी तरफ़, counterclockwise, clockwise, नाक, exhale",
    "Social media खोलने से पहले check करना कि मैं किस state में हूँ",
    "खुद को seriously लेना: अपने field में pro athlete की तरह act करना, rest समेत",
    "अपना edge ढूँढना (सबसे ज़्यादा असली काम जो मैं टिकाऊ ढंग से कर सकूँ), फिर उस average के आसपास काम करना",
    "दिन को समय की unit बनाना: आज मैं क्या कर सकता हूँ, यह जानते हुए कि कल फिर आना है?",
    "हफ़्ते में एक reset day (sunlight फिर भी, लेकिन कोई exercise नहीं और कुछ साबित नहीं करना)",
    "Risk से पहले freeze हो जाऊँ तो stakes कम करना: तीन दिन का commitment, फिर तीन और",
    "Chop wood, carry water: मुश्किल दिनों में बिना 'क्यों' पूछे बस आज का काम करना",
    "Walls के साथ cold shower: बाहर निकलने की एक और urge पार करना (max 3 minutes, ice नहीं)",
    "बिस्तर से उठने से पहले 10 breaths की meditation",
    "अपने work sets को आसान नहीं, मुश्किल बनाना",
    "Overwhelmed होने पर gaze फैलाकर पूरा room देखना, फिर चीज़ें एक-एक करके निपटाना",
    "कुछ ऐसा याद करना जिससे मैं निकला या जो मैंने बनाया, और उसमें अपना हिस्सा मानना",
    "जब notice करूँ तो थोड़ा मुश्किल काम करना",
    "हर book या podcast के बाद self-test: मैंने क्या सीखा? जो याद न आए उसे देखना",
    "कभी खुद पर या दूसरों पर हमला नहीं; कुछ useful न कर सकूँ तो 5 minutes कुछ नहीं करना",
    "बड़े decisions pressure-test करने के लिए respect वाले लोगों की एक committee रखना",
    "Focused काम के दौरान social media अलग phone पर या lock box में रखना",
    '"मैं अभी consumer हूँ या creator?" पूछना और रोज़ कुछ समय create करना',
    "जो चीज़ मैं सबसे ज़्यादा consume करता हूँ, उसका producer बनना",
  ],
};

export function ActionChecklist() {
  return <ChecklistExercise items={useLocalized(ITEMS)} />;
}
