"use client";

import { useLocalized } from "@/components/providers/locale-provider";
import { ChecklistExercise } from "@/components/summary/checklist-exercise";

const ITEMS = {
  en: [
    'Write my "future self" story on paper (from the version of me who already believes) and review it every day',
    'Identify one limiting story I carry ("I\'m a victim", "I can\'t sleep") and rip it up',
    'Use attentional redirection: when the victim story starts, tell my brain "zip it" and go back to the story I want',
    'Write one identity-based belief: identity/value, data, benefits, new habit in one "I\'m the type of person who..." sentence',
    "Turn one goal into an implementation intention (WHEN [exact situation], THEN [tiny first step]), described like a movie",
    "Make the first step tiny (e.g. brush my teeth at 11 p.m. to cut off the kitchen, then pajamas)",
    'For a bad habit: take a cognitive pause and ask "What am I feeling right now?" before acting',
    "Use a 60-second eyes-closed/breathing replacement behavior before scrolling (and allow myself to scroll after, if I still want to)",
    'Stop using scrolling as a "break"; take a real break (walk outside, rest, water, snack, stretch)',
    'Create a phone "parking lot" (a box or another room) for focused work; out of sight, out of mind',
    "Get phones out of the room for important meetings and brainstorms",
    "Keep my phone off the table on coffee chats and dates",
    "Phone off 30 (or 15) minutes before bed and not on until 30 (or 15) minutes after waking",
    "Use the first minutes of the morning to review my beliefs, goals and priorities before any inputs",
    "Turn off computer notifications (Slack, email, watch) during deep work; one task at a time",
    "Accept that multitasking is task switching and batch similar work",
    'Schedule "think time" to be bored and let my mind wander (a little each morning and before bed)',
    "For hard problems: load up the data, then walk away and add a new variable (shower, walk, water, new room)",
    "Change my content diet: unfollow junk accounts, and bloom scroll instead of doom scroll",
    "Try a news cleanse if my mind feels foggy; the world will go on",
    "Watch a 90+ minute movie with no second screen",
    "Prefer long-form content (20-30 minutes of quality YouTube or podcasts); cap short-form at about 10 minutes a day",
    "When lonely, reach out in person or by call/FaceTime/text instead of scrolling social media",
    "Get 7+ hours of quality, unbroken sleep (ideally starting before midnight)",
    "Take the chronotype assessment and find my 2-3 hour peak window",
    "Put creative, admin and deep work in the right windows for my chronotype; work out during my dip",
    "Close my stress cycles: let stress go up and come back down each day",
    "3M breaks: micro (10+ min daily), meso (2-4 h weekly), macro (half to full day monthly), with complete psychological detachment",
    "Pick up a new, challenging active hobby (harmonica, juggling, guitar, a new recipe, a new running route)",
    "Audit and protect what I let into my mind; visualize myself powerful when I feel powerless",
  ],
  hi: [
    'अपनी "future self" story काग़ज़ पर लिखना (उस version की नज़र से जो पहले से believe करता है) और रोज़ review करना',
    'एक limiting story पहचानना जो मैं ढोता हूँ ("I\'m a victim", "मुझे नींद नहीं आती") और उसे फाड़ देना',
    'Attentional redirection: जब victim story शुरू हो, दिमाग़ से कहना "zip it" और अपनी चाही हुई story पर लौटना',
    'एक identity-based belief लिखना: identity/value, data, benefits, new habit, एक "I\'m the type of person who..." sentence में',
    "एक goal को implementation intention में बदलना (WHEN [exact situation], THEN [tiny first step]), movie की तरह describe करके",
    "पहला step tiny रखना (जैसे kitchen बंद करने के लिए रात 11 बजे brush करना, फिर pajamas)",
    'Bad habit के लिए: action से पहले cognitive pause लेकर पूछना "मैं अभी क्या feel कर रहा हूँ?"',
    "Scrolling से पहले 60-second आँखें बंद/breathing वाला replacement behavior (और उसके बाद भी मन हो तो scroll करने की छूट)",
    'Scrolling को "break" मानना बंद करना; real break लेना (बाहर walk, rest, पानी, snack, stretch)',
    'Focused work के लिए phone का "parking lot" बनाना (box या दूसरा कमरा); आँख से दूर, मन से दूर',
    "Important meetings और brainstorms में phones कमरे से बाहर रखना",
    "Coffee chats और dates पर phone table पर न रखना",
    "सोने से 30 (या 15) minute पहले phone off, और उठने के 30 (या 15) minute बाद तक on नहीं",
    "सुबह के पहले minutes में किसी भी input से पहले अपने beliefs, goals और priorities review करना",
    "Deep work के दौरान computer notifications (Slack, email, watch) off; एक समय में एक task",
    "मान लेना कि multitasking असल में task switching है, और मिलते-जुलते काम batch करना",
    'Bore होने और mind wander करने के लिए "think time" schedule करना (रोज़ सुबह और सोने से पहले थोड़ा)',
    "मुश्किल problems के लिए: data load करना, फिर दूर हटकर नया variable जोड़ना (shower, walk, पानी, नया कमरा)",
    "अपनी content diet बदलना: junk accounts unfollow करना, और doom scroll की जगह bloom scroll",
    "दिमाग़ धुंधला लगे तो news cleanse आज़माना; दुनिया चलती रहेगी",
    "बिना second screen के 90+ minute की movie देखना",
    "Long-form content चुनना (20-30 minute का quality YouTube या podcasts); short-form लगभग 10 minute रोज़ तक सीमित",
    "अकेलापन लगे तो social media scroll करने की जगह मिलकर या call/FaceTime/text से संपर्क करना",
    "7+ घंटे की quality, बिना टूटी नींद लेना (हो सके तो आधी रात से पहले शुरू)",
    "Chronotype assessment करना और अपनी 2-3 घंटे की peak window ढूँढना",
    "Creative, admin और deep work को अपने chronotype की सही windows में रखना; dip के दौरान workout",
    "अपने stress cycles close करना: हर दिन stress को ऊपर जाकर वापस नीचे आने देना",
    "3M breaks: micro (रोज़ 10+ min), meso (हर हफ़्ते 2-4 h), macro (हर महीने आधा से पूरा दिन), complete psychological detachment के साथ",
    "कोई नई, challenging active hobby शुरू करना (harmonica, juggling, guitar, नई recipe, नया running route)",
    "जो दिमाग़ में आने देता हूँ उसका audit और बचाव करना; powerless लगे तो ख़ुद को powerful visualize करना",
  ],
};

export function ActionChecklist() {
  return <ChecklistExercise items={useLocalized(ITEMS)} />;
}
